services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_encurtador
    environment:
      POSTGRES_DB: encurtador_url
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - encurtador-network

  app:
    image: ccaueg/encurtador-url:latest
    container_name: encurtador_api
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/encurtador_url
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_BASE_URL: http://localhost:5050
    restart: always
    depends_on:
      - postgres
    networks:
      - encurtador-network

volumes:
  postgres_data:

networks:
  encurtador-network:
    driver: bridge