spring:
  application:
    name: encurtador-url

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/encurtador_url}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  web:
    error:
      include-message: always
      include-binding-errors: always

server:
  port: 5050

app:
  base-url: ${APP_BASE_URL:http://localhost:5050}
  qrcode:
    width: 300
    height: 300

logging:
  level:
    root: INFO
    com.caue.encurtador_url: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME:qrcode-s3-storage}
    region: ${AWS_REGION:us-east-2}